import type { Metadata } from "next";
import "./globals.css";
import Link from "next/link";
import Header from "@/components/header/Header";

export const metadata: Metadata = {
  title: "todo list",
  description: "Generated by soom",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html>
      <body>
        <Header></Header>
        <div className="layout">{children}</div>
      </body>
    </html>
  );
}
